### ISSUE TITLE
ZeroDivisionError in getDupDelcoverage due to awk NR!=1

### ISSUE THREAD

**Issue by wdecoster** [mroosmalen/nanosv#14]
I've come across the following issue:

```
$ NanoSV anon_chr10.bam -s samtools > anon_chr10_nanosv.vcf
Tue Mar 20 14:11:04 2018 Busy with calculating the coverage distribution...
Tue Mar 20 14:17:54 2018 Busy with parsing bam file...
Tue Mar 20 14:32:29 2018 Busy with parsing read segments...
Tue Mar 20 14:32:31 2018 Busy with parsing breakpoints...
Tue Mar 20 14:32:35 2018 Busy with reference reads...
Tue Mar 20 14:33:08 2018 Busy with printing to vcf...
Traceback (most recent call last):
  File "/home/wdecoster/anaconda3/bin/NanoSV", line 11, in <module>
    sys.exit(main())
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/nanosv/NanoSV.py", line 60, in main
    utils.parse_svs.parse_svs()    
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/nanosv/utils/../utils/parse_svs.py", line 49, in parse_svs
    if breakpoint.structural_variants[sv_id_2].set != 1: breakpoint.structural_variants[sv_id_2].setArguments(NanoSV.opts_depth_support)
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/nanosv/utils/../classes/sv.py", line 157, in setArguments
    avg_dupdel_cov = self.getDupDelcoverage()
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/nanosv/utils/../classes/sv.py", line 223, in getDupDelcoverage
    return float(sum(dupdel_coverages)) / len(dupdel_coverages)
ZeroDivisionError: float division by zero
```

It seems this issue happens when `dupdel_coverages` is empty in this function:
https://github.com/mroosmalen/nanosv/blob/9ac4397798848c94ebf99acad58daff927b14c84/nanosv/classes/sv.py#L202
I printed the `cmd` a few lines higher:
`samtools depth anon_chr10.bam -r chr10:425882-425882 | awk '{if (NR!=1) print $3}'`

I believe the `NR!=1` is the source of the error: the bed output of samtools depth in this case has only one line (and no header). As such, this `cmd` returns nothing, leading to an empty `dupdel_coverages`.
I don't know if sambamba does use a header for the output of depth base...

Cheers,
Wouter

**Comment by wdecoster** [comment]
Thanks for the quick fixes!

**Comment by wdecoster** [comment]
Hi,

It looks like you solved the awk NR!=1 error in calculate_coverage_bed() but not in getDupDelcoverage(), I get the same ZeroDivisionError.

https://github.com/mroosmalen/nanosv/blob/ff45be85d7b58fb0ae7a63a7362bfe86896ce7b3/nanosv/classes/sv.py#L218

Cheers,
Wouter

**Comment by mroosmalen** [comment]
Thanks for the issue. This should be fixed now.

**Comment by wdecoster** [comment]
Confirmed!
