### ISSUE TITLE
AttributeError: 'module' object has no attribute 'sample_name'

### ISSUE THREAD

**Issue by ttbond** [mroosmalen/nanosv#17]
Hi~
When I use NanoSV to solve my bam file I meet the error:
‘’‘
Traceback (most recent call last):
  File "/usr/local/bin/NanoSV", line 9, in <module>
    load_entry_point('NanoSV==1.1.2', 'console_scripts', 'NanoSV')()
  File "/usr/local/lib/python2.7/dist-packages/nanosv/NanoSV.py", line 54, in main
    utils.create_vcf.print_vcf_header()
  File "/usr/local/lib/python2.7/dist-packages/nanosv/utils/create_vcf.py", line 21, in print_vcf_header
    vcf = py_vcf.Reader(io.StringIO("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\t"+ str(bam.sample_name)))
AttributeError: 'module' object has no attribute 'sample_name'
’‘’

Could u give me any help ? THX A LOT.

**Comment by mroosmalen** [comment]
Can you please send me the command, what you try to run? 
And do you know if there is the SM tag in your bam header or not?

**Comment by ttbond** [comment]
Thx for your reply:)
==============================================
Part of the headers:
@RG     ID:allData-1B5350E6     SM:UMCUTRIO-001-C
@RG     ID:allData-40265BF      SM:UMCUTRIO-001-C
@RG     ID:allData-39545E27     SM:UMCUTRIO-001-C
@RG     ID:allData-2A3AB999     SM:UMCUTRIO-001-C
@RG     ID:allData-28A895F8     SM:UMCUTRIO-001-C
@RG     ID:allData-28DCFA1B     SM:UMCUTRIO-001-C
@RG     ID:allData-2D7AA89A     SM:UMCUTRIO-001-C
@RG     ID:allData-192FC230     SM:UMCUTRIO-001-C
=============================
My command:
NanoSV -s samtools '/media/ttbond/00017CAE00095FC0/Nanopore/DNA181/21sorted.bam'
=============================

**Comment by mroosmalen** [comment]
I can't reproduce the error. When I try to run it with a similar head ( with @rg ) I get the following error:
```
AssertionError: header line with invalid type 'rg': '@rg ID:allData-1B5350E6    SM:UMCUTRIO-001-C'
```
When I change the @rg to capitals @RG then it works. Can you try this?

Do you know which version of pysam you use and which version of samtools? Maybe there is a problem with the versions.

**Comment by ttbond** [comment]
I didn't notice that when I copy the header to this editor the 'RG' became 'rg'.
Actually, part of the header is:
`@RG     ID:allData-46B4BC84     SM:UMCUTRIO-001-C
@RG     ID:allData-72D0E196     SM:UMCUTRIO-001-C
@RG     ID:allData-69A87AE6     SM:UMCUTRIO-001-C
@RG     ID:allData-7F3630DC     SM:UMCUTRIO-001-C
@RG     ID:allData-F7AB04E      SM:UMCUTRIO-001-C
@RG     ID:allData-7D109CF9     SM:UMCUTRIO-001-C
@RG     ID:allData-78A99B59     SM:UMCUTRIO-001-C
@RG     ID:allData-51FFCAE6     SM:UMCUTRIO-001-C
@RG     ID:allData-6E5D5B5D     SM:UMCUTRIO-001-C
@RG     ID:allData-CB3A259      SM:UMCUTRIO-001-C
`

The samtools version is 1.7.
I don't know where to find the NanoSV version, but I  updated it by pip one hour ago.

**Comment by mroosmalen** [comment]
I see that you use python2.7 modules ```File "/usr/local/lib/python2.7/dist-packages/nanosv/NanoSV.py", line 54, in main``` and NanoSV needs python3. 

Can you try to install NanoSV again under python3?

**Comment by ttbond** [comment]
That works! Thanks very very very much for your help!
And It's really cool that the latest version supports the bam file with several RG tags!
And also the redundant prints in old version were also canceled!
The tool is really cool and very helpful!~
