### ISSUE TITLE
Use multiple processes

### ISSUE THREAD

**Issue by wdecoster** [mroosmalen/nanosv#20]
Hi,

I'm running NanoSV on our PromethION genomes, and I think quite some time can be saved by using multiple processes, e.g. by splitting `sambamba/samtools depth` per chromosome. If you want I'd be happy to try this. A -t/--threads argument could be added to allow the user to adapt to the number of threads available.

Cheers,
Wouter

**Comment by mroosmalen** [comment]
We will try to implement multi-threading in the future

**Comment by wdecoster** [comment]
Another suggestion if I may: perhaps you could consider also allowing [mosdepth](https://github.com/brentp/mosdepth) as a tool for calculating coverage in addition to samtools/sambamba. It's pretty fast but unfortunately writes to files rather than stdout.
