### ISSUE TITLE
Instructions on generating BED file reference

### ISSUE THREAD

**Issue by adelq** [mroosmalen/nanosv#21]
Could you provide the code used to generate the default bed file (`human_hg19.bed`)? I see that the general methodology is provided in the README, but a script for complete reproducibility would be appreciated. I am guessing `bedtools random` was used, but I'm not sure how the repeat and gap regions were excluded.

**Comment by mroosmalen** [comment]
I wrote my own python script to generate a bed file.

[create_random_position_bed.py.zip](https://github.com/mroosmalen/nanosv/files/1918303/create_random_position_bed.py.zip)

**Comment by adelq** [comment]
Awesome, thanks.

**Comment by ChaoTang-SCU** [comment]
Hi,
Can you give a demo of human_hg19.bed file? Or describe clearly what this file should look like? I want to use nanosv on a new species and I don't know how to prepare this file. Thanks very much.

**Comment by jaesvi** [comment]
Hi,
it should look like chrom\tpos\tpos+1
`1	10577	10578

1	13313	13314

1	16429	16430

1	18942	18943

1	19583	19584

1	20791	20792

1	30496	30497

1	30704	30705

1	31743	31744

1	33880	33881

`
We use 1,000,000 positions in this file
