### ISSUE TITLE
coverage 

### ISSUE THREAD

**Issue by njaupan** [mroosmalen/nanosv#29]
Hi, 

I have update nanosv to 1.1.6, command as followed but error occurred: 
$NanoSV -s /home/sophie/sambamba '/home/sophie/Desktop/nanosv/maf.sorted.bam' 

Can't calculate coverage distribution. The bed file may be inappropriate for your bam file.

Bam files which obtained from LAST worked on Sniffes.
Do you have any suggestion?

Thank you,
panpan

**Comment by mroosmalen** [comment]
Which reference genome did you used for mapping? And is there the 'chr' notation in front of  the chromosomes in your bam file?

**Comment by njaupan** [comment]
I have used Arabidopsis TAIR10 as reference genome, the fasta header was changed to chr01, chr02...and chr05 before using LAST alignment.

**Comment by mroosmalen** [comment]
The default bed file is based on the human reference genome, that is why you get this error message. You can create your own bed file and give this with the -b parameter. Or  disable the coverage depth support function by creating a config.ini file like:
'''
[Detection options]
depth_support = False
'''
and give this with the -c parameter

**Comment by njaupan** [comment]
thank you, now it is working.

**Comment by njaupan** [comment]
Thank you. i have add both -b -c parameter and then it works. However, only -b is not working, showing same results as "Can't calculate coverage distribution. The bed file may be inappropriate for your bam file". any suggestion to predict breakpoint-junctions while turn on depth_support ?

**Comment by jaesvi** [comment]
You need to create a BED file with 1,000,000 random positions in your own genome of interest. We only provide the one that we use for hg19/GRCh37 human genome reference. In the "scripts" you can see how we created the human one with a python script.

**Comment by njaupan** [comment]
i see, thank you.
