### ISSUE TITLE
Documentation on parameters  

### ISSUE THREAD

**Issue by MattBashton** [mroosmalen/nanosv#3]
I think the parameters you provide make your program highly tuneable and adaptable more so than many other SV detectors - which is a really good thing! However, many of the descriptions for parameters are not clear, this makes it difficult for an end user to fully adapt the running of the program for their specific usage case / SVs of intrest.  Some of these arguments are more ambiguous than others could you please elaborate on the descriptions or of offer examples of what these are doing. Specific parameters that I find the descriptions a bit too terse are:

**Filter options:**

`-split` what do you mean by "segments" are these supplemental alignments for each read or contagious stretches of the read which align without indels or something else? 
`-pid` Is this the percentage identity of a read to be considered as counting towards an SV with `-count` those below this not counting?

**Detection options:**

`-refdistance` It's not at all clear to me what a reference read is? I expect most of the reads have been mapped to the reference by LAST is this what you mean?  Also what do you mean by distance?  What is the distance to / from?

`-matedistance` My MinION data is not mate paired, is it possible to have paired data?  How will this impact data generated without pairs?  What is mateid used for when found?

**Filter output options**

`-pidf` and `-mapqf`: Is the median identity / mapping quality calculated from supporting reads which belong to an SV?

`-gap` It's not clear what this is, gap between what exactly, I know it's for non-insertions from the VCF header but would this effectively filter out translocations at distance from each other?  Ideally I specifically want to detect events at distance, can this filter be disabled?

`-ci` it's not clear what this confidence interval is or how it's calculated?

**Comment by MattBashton** [comment]
Also the value of `-pidf` would appear to not be propagating into the VCF header.

**Comment by mroosmalen** [comment]
I will elaborate the settings soon. More details can also be found in our paper.

Cretu Stanu, M. _et al._ (2017) Mapping and phasing of structural variation in patient genomes using nanopore sequencing. _Nat Commun_; 8 1326 https://dx.doi.org/10.1038%2Fs41467-017-01343-4

**Comment by MattBashton** [comment]
Thank you very much for the paper link would be good to see that in the main README.md (plus you get more citations! ;) ) , I've only been using the program for an hour or two and it looks very useful, but it's a bit difficult to get a handle on the filtration / detection options, so thought some feedback on that might be useful as I'm sure others will find this information helpful!
