### ISSUE TITLE
error of last-train

### ISSUE THREAD

**Issue by HuJane** [mroosmalen/nanosv#32]
Dear Mroosmalen,
I've got some problem when ran last-train. Firstly, I thought it was because of the python version, but after I changed from 3 to 2, the error was still appeared...

pyenv versions
  system
* 2.7.14 (set by /home/hujie/nanopore/sv/.python-version)
  3.6.5

last-train -P8 -Q1 ../hg38db ../assembly/DDEX.fastq > my-params
last-train: error: a bytes-like object is required, not 'str'

**Comment by mroosmalen** [comment]
I did not get this error when I used last-train. Maybe it is a version problem of LAST? I used last-921.
Maybe you can contact the authors of LAST via http://last.cbrc.jp/doc/last.html.

**Comment by wdecoster** [comment]
FWIW, I have to run last-train like this:
```
python2.7 `which last-train`
```

I'm not sure, but upon installation it seems last-train got prefixed (on my system) with
```
#!/home/wdecoster/anaconda3/bin/python
```

which is python3.

Cheers,
Wouter

**Comment by jaesvi** [comment]
We'd love to help but it is probably better to contact the maintainers of LAST for this issues.
