### ISSUE TITLE
ID and MATEID

### ISSUE THREAD

**Issue by tgong1** [mroosmalen/nanosv#48]
Hi,

I'm wondering the relationship between SV(BND) reported with MATEID as same as ID of another SV(BND), like the following two SV(BNDs) ? Thank you very much!

#CHROM | POS | ID | REF | ALT | QUAL | FILTER | INFO | FORMAT | sample
chr1 | 180985284 | 995 | T | [chr1:180985351[T | 60 | MapQual | SVTYPE=BND;SVMETHOD=NanoSV_v1.1.6;CIPOS=0,0;CIEND=0,0;SVLEN=67;RT=0,1,0;GAP=-16;MAPQ=60,60;PID=0.966,0.982;PLENGTH=0.531,0.425;RLENGTH=786;MATEID=3240 | GT:DR:DV:GQ:HR:PL | 1/1:0,0:1,1:6:0,0:60,6,0

chr1 | 180984989 | 3240 | T | T]chr1:180985293] | 48 | MapQual | SVTYPE=BND;SVMETHOD=NanoSV_v1.1.6;CIPOS=0,0;CIEND=0,0;SVLEN=304;RT=0,1,0;GAP=15;MAPQ=53,60;PID=0.947,0.969;PLENGTH=0.206,0.668;RLENGTH=921;MATEID=995 | GT:DR:DV:GQ:HR:PL | 0/1:2,0:1,1:9:0,0:48,0,9

**Comment by mroosmalen** [comment]
In a case of an inversion (like in your example) the SVs consits of two breakends (BND) with a TT orientation and HH orientation. In your case:

```
          ID=3240      ID=995
            TT          HH
chr1 >>>>>>>||<<<<<<<<<<||>>>>>>>
        ..989       ..284
           ..293       ..351 (those coordinates are always based on the reference genome)
```

NanoSV will consider a MATEID if the distance between two start positions (POS) is <= 300 bp and between the two end positions (ALT) is <= 300bp (see config.ini mate_distance) and with opposite orientation (eg. HH and TT).

We are planning to make a supplementary script for annotation and merge breakends at the end to a single inversion for example.
