### ISSUE TITLE
Provided Bedfile is not hg19 coordinate

### ISSUE THREAD

**Issue by zhouanbo** [mroosmalen/nanosv#49]
Hi,
It seems that the provided bed file is b37 coordinate (without "chr" before chromosome numbers), and when liftover the bed file to hg19, the program exits with:
```
Traceback (most recent call last):
  File "/home/user/miniconda2/envs/nanosv/bin/NanoSV", line 11, in <module>
    sys.exit(main())
  File "/home/user/miniconda2/envs/nanosv/lib/python3.6/site-packages/nanosv/NanoSV.py", line 76, in main
    utils.parse_svs.parse_svs()
  File "/home/user/miniconda2/envs/nanosv/lib/python3.6/site-packages/nanosv/utils/../utils/parse_svs.py", line 55, in parse_svs
    breakpoint.structural_variants[sv_id_2].setArguments(NanoSV.opts_depth_support)
  File "/home/user/miniconda2/envs/nanosv/lib/python3.6/site-packages/nanosv/utils/../classes/sv.py", line 159, in setArguments
    avg_dupdel_cov = self.getDupDelcoverage()
  File "/home/user/miniconda2/envs/nanosv/lib/python3.6/site-packages/nanosv/utils/../classes/sv.py", line 225, in getDupDelcoverage
    return float(sum(dupdel_coverages)) / len(dupdel_coverages)
ZeroDivisionError: float division by zero
Command exited with non-zero status 1

```

**Comment by mroosmalen** [comment]
It looks like that the dupdel_coverages list is empty. This means there are no positions between the start and end of an sv, or the depth function returns an error. Can you try the following command, to check the depth function:
```
$SAMBAMBA depth base --min-coverage=0 $BAM -L $CHR:$START-$END
```
or is you use samtools:
```
$SAMTOOLS depth $BAM -r $CHR:$START-$END
```

**Comment by zhouanbo** [comment]
I tested with the liftover bed file, sambamba output an error: 
```
core.exception.AssertError@/gnu/store/sp0qvwcw5yhv4mi32sabzpi8jid47gh7-ldc-1.1.1/include/d/std/parallelism.d(1825): null this
```

**Comment by mroosmalen** [comment]
The problem is then with sambamba. You can try to contact the authors of sambamba and report there this issue. Normally it should work with sambamba and/or samtools. Maybe you can try to run it with samtools?

**Comment by mroosmalen** [comment]
Can you add the next line to the classes/sv.py just above line 225
```
print(cmd)
```
This will print the sambamba command (just above the error) that it try to execute and then try to execute this on the command line.

Or maybe you can shared the bam file if it's not too big?

**Comment by zhouanbo** [comment]
Hi, 
I added the code and it outputs a lot of commands, the last one it output before the "division by zero" crash is: 
```
sambamba depth base --min-coverage=0 sort.bam -L chr10:72942148-72942182 --nthreads=16 2> /dev/null | awk '{if (NR!=1) print $3}'
```
which prints nothing, while others prints a list of numbers. Maybe there's no coverage at that region, is there a way to prevent the crash?

**Comment by mroosmalen** [comment]
Hmmm strange, if there's no coverage at that region the output should be like:
```
REF	POS	COV	A	C	G	T	DEL	REFSKIP	SAMPLE
10	72942147	0	0	0	0	0	0	0	A
10	72942148	0	0	0	0	0	0	0	A
10	72942149	0	0	0	0	0	0	0	A
10	72942150	0	0	0	0	0	0	0	A
```

Can you try to run the command without catching the stderr, like:
```
sambamba depth base --min-coverage=0 sort.bam -L chr10:72942148-72942182 --nthreads=16
```

**Comment by mroosmalen** [comment]
This could indeed the problem. Maybe you can try to run it with samtools.

**Comment by zhouanbo** [comment]
Hi,

It turns out that Samtools updated it's BAM specification to deal with long CIGAR strings in version 1.7 (https://github.com/samtools/samtools/releases/tag/1.7), and sambamba is not compatible with the bam files samtools generated. That's what is causing the problem. After switching to samtools the program runs fine.
