### ISSUE TITLE
how to correctly convert maf to sam

### ISSUE THREAD

**Issue by fcdn007** [mroosmalen/nanosv#5]
"maf-convert sam" can convert maf files prouced by LAST to sam. But for a read with multiple fragments which are needed by nanosv, the program could only write the last one to the result sam file so that nanosv  couldn't find any SV. How to fix this problem?

**Comment by mroosmalen** [comment]
I never saw this problem. Did you use last-split like: 
lastal -Q1 -p my-params humandb reads.fastq | last-split > reads.maf

And then use the maf-convert script
