### ISSUE TITLE
Conda install nanosv 1.2.4

### ISSUE THREAD

**Issue by max1c** [mroosmalen/nanosv#58]
Are there plans to add the 1.2.4 release to Conda?

**Comment by jaesvi** [comment]
Hi @wdecoster , could you help me out here? If I remember correctly, you added the original bioconda recipe, so it would be nice to update the version.
Aprreciated,
Jose

**Comment by wdecoster** [comment]
Sure no problem, but I see 1.2.4 is also not yet on [PyPI](https://pypi.org/project/NanoSV/#history)?
Conda packages are based on those on PyPI so if that one can be updated I'll take care of the conda recipe.

**Comment by wdecoster** [comment]
Alternatively, the conda recipe can also be based on a GitHub release, if you make one for v1.2.4

**Comment by jaesvi** [comment]
I just uploaded it to PyPI. Thanks a lot for your help!

**Comment by wdecoster** [comment]
My pull request for updating the bioconda recipe will be merged soon.

**Comment by max1c** [comment]
> My pull request for updating the bioconda recipe will be merged soon.

Thanks, installed and tested. Everything is working.

**Comment by jaesvi** [comment]
Nice, thanks a lot @wdecoster

**Comment by wdecoster** [comment]
Happy to help, feel free to let me know if you have a new version available.

**Comment by druvus** [comment]
The bioconda-bot should pick up future releases at pypi.
