### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by amrita1983** [mroosmalen/nanosv#6]
Hi,
I tried to run nanosv for my ngmlr bam file, but the error came like this

Can't locate Read.pm in @INC (@INC contains: /export/apps/miniconda/bin /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.8.8 /usr/lib/perl5/vendor_perl /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/5.8.8 .) at nanosv.pl line 14.
BEGIN failed--compilation aborted at nanosv.pl line 14.

please help

**Comment by mroosmalen** [comment]
The Read.pm file ( and all other files ) should be in the same directory as nanosv.pl

**Comment by amrita1983** [comment]
Hi,

Thanks for the reply, but how can i g et them in the same folder can you please guide me on that. I am using Miniconda to run the same.

**Comment by mroosmalen** [comment]
This version is written in perl.
Where busy with rewriting nanosv in python. I hope we will finish this by the end of this week or beginning of next week.

**Comment by wdecoster** [comment]
Oh good to hear you are rewriting to Python :-) guess I'll wait a bit longer then before I start testing NanoSV.
