### ISSUE TITLE
cannot call NanoSV after installing with conda

### ISSUE THREAD

**Issue by BCArg** [mroosmalen/nanosv#60]
I have installed nanosv on a virtual environment with `conda install -c bioconda nanosv`.

I then got a strange message before confirming the installation:
```
(ont37) ngs@cr28603:~> conda install -c bioconda nanosv
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
```

Then I was asked whether I wanted to install the package. After I hit yes it appeared that the package was successfully installed. If I do `conda list`, I see a line for nanosv:
```
nanosv                    0.0.1                pl5.22.0_0    bioconda
```

Though it does not appear that the correct version was installed. When I type `Nano` the only autocompletion that I get is from another package `NanoPlot` whereas if I type `nano` I get `nanosv.pl` as autocompletion suggestion.

On another computer I have installed it with `pip install nanosv` and it is working, apparently with the latest version `NanoSV 1.2.3`.

**Comment by jaesvi** [comment]
Hi, could you reinstall it? We just updated the version stored in bioconda.

**Comment by BCArg** [comment]
It works now thanks
