### ISSUE TITLE
what is an appropriate bed file?

### ISSUE THREAD

**Issue by yekaizhou** [mroosmalen/nanosv#74]
Hello,

I ran NanoSV like this: `NanoSV -t 40 -o nanosv.vcf -b human_hg19.bed aln.bam`, and it prompted `The bed file may be inappropriate for your bam file.`

The bed file is downloaded from your curation `https://github.com/mroosmalen/nanosv/blob/master/nanosv/bedfiles/human_hg19.bed`

The bam file is some ~8X ONT data downloaded from `https://ftp.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/UCSC_Ultralong_OxfordNanopore_Promethion/GM24385_1.fastq.gz`, and then aligned to `hs37d5`, which can be perfectly ran on several other SV tools e.g. cuteSV, sniffles, svim.

I am wondering if I used NanoSV incorrectly and how can I adjust, and it seems to be the problem of the bed file. What I should do with the bed file?

**Comment by kztyes** [comment]
I also have this problem. Even if I use Samtools to generate a new bed file, it is still inappropriate for BAM files

**Comment by fishercera** [comment]
Bumping this. 

I used bedtools to generate a random-spot BEDfile, after reading the scripts that are included to generate such. I did:

`bedtools random -l 1 -seed 1938 -g Aedes_chr1.genome > Aedes_chrom1_randomspots.bed`

Where "Aedes_chr1.genome" is just a two column file giving the length of Chromosome 1 - 

`1       310827022`

I'm not sure if this is the right thing to do, but it has actually resulted in NanoSV giving me results, after 10 days of running...

**Comment by Mrromeros** [comment]
If you align your data to GRCH37, it will work with the default bed file they have, which is mislabeled hg19
