### ISSUE TITLE
Make version numbers more obvious

### ISSUE THREAD

**Issue by datakid** [mroosmalen/nanosv#9]
Thanks for your work. 

Because I install this into a multi-user system using module files, I use version numbers to control access. 

Before I install this software, the only version number I can see is the last git commit hash: 5f44e1.

After installation I discover via pip list that this is version 1.0.4. 

Would be great if there could be some way to know that version number before installation - either via a version file or a release tarball?

**Comment by mroosmalen** [comment]
There is a version file:
https://github.com/mroosmalen/nanosv/blob/master/nanosv/version.py
